### ISSUE TITLE
Hitting errors on Purchases tab

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/uc_civicrm#2]
On screen:
![screen shot 2018-05-15 at 1 54 08 pm](https://user-images.githubusercontent.com/871421/40077506-7ddd378e-5847-11e8-9b13-0e7fc5488fc9.jpg)

In the log:

```
May 15 13:49:49  [info] $Fatal Error Details = Array
(
    [message] => We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.&lt;br /&gt;&lt;br /&gt;Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.&lt;br /&gt;&lt;br /&gt;Error type: Could not find a valid session key.
    [code] => 
)


May 15 13:49:49  [info] $backTrace = #0 /home/backdrop/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/backdrop/modules/civicrm/CRM/Core/Controller.php(833): CRM_Core_Error::fatal("We can't load the requested web page. This page requires cookies to be enable...")
#2 /home/backdrop/modules/civicrm/CRM/Core/Controller.php(828): CRM_Core_Controller->invalidKeyCommon()
#3 /home/backdrop/modules/civicrm/CRM/Core/Controller.php(312): CRM_Core_Controller->invalidKey()
#4 /home/backdrop/modules/civicrm/CRM/Core/Controller.php(204): CRM_Core_Controller->key("CRM_Profile_Form_Dynamic", TRUE, FALSE)
#5 /home/backdrop/modules/civicrm/CRM/Core/Controller/Simple.php(66): CRM_Core_Controller->__construct("Dynamic Form Creator", TRUE, 2, "CRM_Profile_Form_Dynamic", TRUE, FALSE)
#6 /home/backdrop/modules/civicrm/CRM/Core/BAO/UFGroup.php(834): CRM_Core_Controller_Simple->__construct("CRM_Profile_Form_Dynamic", "Dynamic Form Creator", 2)
#7 /home/backdrop/modules/civicrm/backdrop/civicrm_user.inc(80): CRM_Core_BAO_UFGroup::getEditHTML(34718, "", 2, TRUE, FALSE, NULL, FALSE, "Individual")
#8 /home/backdrop/core/includes/module.inc(947): civicrm_user_insert(Object(User))
#9 /home/backdrop/core/modules/entity/entity.controller.inc(602): module_invoke_all("user_insert", Object(User))
#10 /home/backdrop/core/modules/entity/entity.controller.inc(539): EntityDatabaseStorageController->invokeHook("insert", Object(User))
#11 /home/backdrop/core/modules/user/user.entity.inc(257): EntityDatabaseStorageController->save(Object(User))
#12 /home/backdrop/core/modules/entity/entity.class.inc(143): UserStorageController->save(Object(User))
#13 /home/backdrop/core/modules/user/user.entity.inc(173): Entity->save()
#14 /home/backdrop/modules/ubercart/uc_order/uc_order.admin.inc(576): User->save()
#15 /home/backdrop/core/includes/form.inc(1542): uc_order_create_form_create_submit((Array:29), (Array:22))
#16 /home/backdrop/core/includes/form.inc(920): form_execute_handlers("submit", (Array:29), (Array:22))
#17 /home/backdrop/core/includes/form.inc(385): backdrop_process_form("uc_order_create_form", (Array:29), (Array:22))
#18 /home/backdrop/core/includes/form.inc(131): backdrop_build_form("uc_order_create_form", (Array:22))
#19 /home/backdrop/core/modules/system/system.module(2401): backdrop_get_form("uc_order_create_form")
#20 /home/backdrop/core/includes/module.inc(914): system_block_view("main", (Array:0), (Array:1))
#21 /home/backdrop/core/modules/layout/includes/block_legacy.class.inc(24): module_invoke("system", "block_view", "main", (Array:0), (Array:1))
#22 /home/backdrop/core/modules/layout/includes/block_legacy.class.inc(50): BlockLegacy->buildBlock()
#23 /home/backdrop/core/modules/layout/plugins/renderers/layout_renderer_standard.inc(507): BlockLegacy->getContent()
#24 /home/backdrop/core/modules/layout/plugins/renderers/layout_renderer_standard.inc(461): LayoutRendererStandard->renderBlock(Object(BlockLegacy))
#25 /home/backdrop/core/modules/layout/plugins/renderers/layout_renderer_standard.inc(368): LayoutRendererStandard->renderBlocks()
#26 /home/backdrop/core/modules/layout/plugins/renderers/layout_renderer_standard.inc(348): LayoutRendererStandard->renderLayout()
#27 /home/backdrop/core/modules/layout/layout.module(469): LayoutRendererStandard->render()
#28 /home/backdrop/core/includes/menu.inc(529): layout_route_handler((Array:31))
#29 /home/backdrop/index.php(21): menu_execute_active_handler()
#30 {main}
```

**Comment by laryn** [comment]
This is fixed in the latest commits. Snippet needed to be returned as JSON for more recent versions of CiviCRM.

> `CRM_Core_Page_AJAX::returnJsonResponse(render($output));`
